version: '3'

services: 
  app:
    build: .
    entrypoint: ./entrypoint.sh
    container_name: descomplica-api-nestjs
    ports:
      - 3333:3333
    volumes: 
      - .:/home/node/app
    environment:
      - DATABASE_MONGOOSE_USER=DATABASE_MONGOOSE_USER
      - DATABASE_MONGOOSE_PASSWORD=DATABASE_MONGOOSE_PASSWORD
      - DATABASE_MONGOOSE_NAME=DATABASE_MONGOOSE_NAME
      - FRONTEND_URL=http://localhost:3000
      - FRONTEND_URL_PRODUCTION=FRONTEND_URL_PRODUCTION